//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.11 at 06:37:51 PM CEST 
//


package eu.mapperproject.mad.specification;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.mapperproject.mad.specification package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Position_QNAME = new QName("http://www.mapper-project.eu/mad", "position");
    private final static QName _PortMapping_QNAME = new QName("http://www.mapper-project.eu/mad", "portMapping");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.mapperproject.mad.specification
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Position }
     * 
     */
    public Position createPosition() {
        return new Position();
    }

    /**
     * Create an instance of {@link PortMapper }
     * 
     */
    public PortMapper createPortMapper() {
        return new PortMapper();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Position }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mapper-project.eu/mad", name = "position")
    public JAXBElement<Position> createPosition(Position value) {
        return new JAXBElement<Position>(_Position_QNAME, Position.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PortMapper }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mapper-project.eu/mad", name = "portMapping")
    public JAXBElement<PortMapper> createPortMapping(PortMapper value) {
        return new JAXBElement<PortMapper>(_PortMapping_QNAME, PortMapper.class, null, value);
    }

}
