//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.04 at 02:59:48 PM CEST 
//


package eu.mapperproject.xmml.specification;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.mapper-project.eu/xmml}datatype" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element ref="{http://www.mapper-project.eu/xmml}filter"/>
 *           &lt;element ref="{http://www.mapper-project.eu/xmml}mapper"/>
 *           &lt;element ref="{http://www.mapper-project.eu/xmml}submodel"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;anyAttribute/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "datatype",
    "filterOrMapperOrSubmodel"
})
@XmlRootElement(name = "definitions")
public class Definitions {

    protected List<Datatype> datatype;
    @XmlElements({
        @XmlElement(name = "filter", type = Filter.class),
        @XmlElement(name = "submodel", type = Submodel.class),
        @XmlElement(name = "mapper", type = Mapper.class)
    })
    protected List<Object> filterOrMapperOrSubmodel;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the datatype property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the datatype property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDatatype().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Datatype }
     * 
     * 
     */
    public List<Datatype> getDatatype() {
        if (datatype == null) {
            datatype = new ArrayList<Datatype>();
        }
        return this.datatype;
    }

    /**
     * Gets the value of the filterOrMapperOrSubmodel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the filterOrMapperOrSubmodel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFilterOrMapperOrSubmodel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Filter }
     * {@link Submodel }
     * {@link Mapper }
     * 
     * 
     */
    public List<Object> getFilterOrMapperOrSubmodel() {
        if (filterOrMapperOrSubmodel == null) {
            filterOrMapperOrSubmodel = new ArrayList<Object>();
        }
        return this.filterOrMapperOrSubmodel;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

}
