//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.04 at 02:59:48 PM CEST 
//


package eu.mapperproject.xmml.specification;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.mapperproject.xmml.specification package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Total_QNAME = new QName("http://www.mapper-project.eu/xmml", "total");
    private final static QName _Delta_QNAME = new QName("http://www.mapper-project.eu/xmml", "delta");
    private final static QName _Description_QNAME = new QName("http://www.mapper-project.eu/xmml", "description");
    private final static QName _Extra_QNAME = new QName("http://www.mapper-project.eu/xmml", "extra");
    private final static QName _In_QNAME = new QName("http://www.mapper-project.eu/xmml", "in");
    private final static QName _Out_QNAME = new QName("http://www.mapper-project.eu/xmml", "out");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.mapperproject.xmml.specification
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Implementation }
     * 
     */
    public Implementation createImplementation() {
        return new Implementation();
    }

    /**
     * Create an instance of {@link Library }
     * 
     */
    public Library createLibrary() {
        return new Library();
    }

    /**
     * Create an instance of {@link Spacescale }
     * 
     */
    public Spacescale createSpacescale() {
        return new Spacescale();
    }

    /**
     * Create an instance of {@link Timescale }
     * 
     */
    public Timescale createTimescale() {
        return new Timescale();
    }

    /**
     * Create an instance of {@link Platform }
     * 
     */
    public Platform createPlatform() {
        return new Platform();
    }

    /**
     * Create an instance of {@link Submodel }
     * 
     */
    public Submodel createSubmodel() {
        return new Submodel();
    }

    /**
     * Create an instance of {@link Range }
     * 
     */
    public Range createRange() {
        return new Range();
    }

    /**
     * Create an instance of {@link Instance }
     * 
     */
    public Instance createInstance() {
        return new Instance();
    }

    /**
     * Create an instance of {@link Param }
     * 
     */
    public Param createParam() {
        return new Param();
    }

    /**
     * Create an instance of {@link Filter }
     * 
     */
    public Filter createFilter() {
        return new Filter();
    }

    /**
     * Create an instance of {@link Datatype }
     * 
     */
    public Datatype createDatatype() {
        return new Datatype();
    }

    /**
     * Create an instance of {@link Topology }
     * 
     */
    public Topology createTopology() {
        return new Topology();
    }

    /**
     * Create an instance of {@link Apply }
     * 
     */
    public Apply createApply() {
        return new Apply();
    }

    /**
     * Create an instance of {@link Definitions }
     * 
     */
    public Definitions createDefinitions() {
        return new Definitions();
    }

    /**
     * Create an instance of {@link Coupling }
     * 
     */
    public Coupling createCoupling() {
        return new Coupling();
    }

    /**
     * Create an instance of {@link Otherscale }
     * 
     */
    public Otherscale createOtherscale() {
        return new Otherscale();
    }

    /**
     * Create an instance of {@link Port }
     * 
     */
    public Port createPort() {
        return new Port();
    }

    /**
     * Create an instance of {@link Model }
     * 
     */
    public Model createModel() {
        return new Model();
    }

    /**
     * Create an instance of {@link AnyContent }
     * 
     */
    public AnyContent createAnyContent() {
        return new AnyContent();
    }

    /**
     * Create an instance of {@link Ports }
     * 
     */
    public Ports createPorts() {
        return new Ports();
    }

    /**
     * Create an instance of {@link Mapper }
     * 
     */
    public Mapper createMapper() {
        return new Mapper();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Range }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mapper-project.eu/xmml", name = "total")
    public JAXBElement<Range> createTotal(Range value) {
        return new JAXBElement<Range>(_Total_QNAME, Range.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Range }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mapper-project.eu/xmml", name = "delta")
    public JAXBElement<Range> createDelta(Range value) {
        return new JAXBElement<Range>(_Delta_QNAME, Range.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnyContent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mapper-project.eu/xmml", name = "description")
    public JAXBElement<AnyContent> createDescription(AnyContent value) {
        return new JAXBElement<AnyContent>(_Description_QNAME, AnyContent.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnyContent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mapper-project.eu/xmml", name = "extra")
    public JAXBElement<AnyContent> createExtra(AnyContent value) {
        return new JAXBElement<AnyContent>(_Extra_QNAME, AnyContent.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Port }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mapper-project.eu/xmml", name = "in")
    public JAXBElement<Port> createIn(Port value) {
        return new JAXBElement<Port>(_In_QNAME, Port.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Port }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.mapper-project.eu/xmml", name = "out")
    public JAXBElement<Port> createOut(Port value) {
        return new JAXBElement<Port>(_Out_QNAME, Port.class, null, value);
    }

}
