//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.04 at 02:59:48 PM CEST 
//


package eu.mapperproject.xmml.specification;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.mapper-project.eu/xmml}description" minOccurs="0"/>
 *         &lt;element ref="{http://www.mapper-project.eu/xmml}timescale"/>
 *         &lt;element ref="{http://www.mapper-project.eu/xmml}spacescale" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.mapper-project.eu/xmml}otherscale" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.mapper-project.eu/xmml}param" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.mapper-project.eu/xmml}ports"/>
 *         &lt;element ref="{http://www.mapper-project.eu/xmml}implementation" minOccurs="0"/>
 *         &lt;element ref="{http://www.mapper-project.eu/xmml}extra" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.mapper-project.eu/xmml}realObject"/>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="init" type="{http://www.mapper-project.eu/xmml}YesNoChoice" default="no" />
 *       &lt;attribute name="interactive" type="{http://www.mapper-project.eu/xmml}OptionalChoice" default="no" />
 *       &lt;attribute name="stateful" type="{http://www.mapper-project.eu/xmml}OptionalChoice" default="no" />
 *       &lt;anyAttribute/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "description",
    "timescale",
    "spacescale",
    "otherscale",
    "param",
    "ports",
    "implementation",
    "extra"
})
@XmlRootElement(name = "submodel")
public class Submodel {

    protected AnyContent description;
    @XmlElement(required = true)
    protected Timescale timescale;
    protected List<Spacescale> spacescale;
    protected List<Otherscale> otherscale;
    protected List<Param> param;
    @XmlElement(required = true)
    protected Ports ports;
    protected Implementation implementation;
    protected List<AnyContent> extra;
    @XmlAttribute
    protected String name;
    @XmlAttribute
    protected YesNoChoice init;
    @XmlAttribute
    protected OptionalChoice interactive;
    @XmlAttribute
    protected OptionalChoice stateful;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String id;
    @XmlAttribute(name = "class")
    protected String clazz;
    @XmlAttribute
    protected String version;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link AnyContent }
     *     
     */
    public AnyContent getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnyContent }
     *     
     */
    public void setDescription(AnyContent value) {
        this.description = value;
    }

    /**
     * Gets the value of the timescale property.
     * 
     * @return
     *     possible object is
     *     {@link Timescale }
     *     
     */
    public Timescale getTimescale() {
        return timescale;
    }

    /**
     * Sets the value of the timescale property.
     * 
     * @param value
     *     allowed object is
     *     {@link Timescale }
     *     
     */
    public void setTimescale(Timescale value) {
        this.timescale = value;
    }

    /**
     * Gets the value of the spacescale property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the spacescale property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSpacescale().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Spacescale }
     * 
     * 
     */
    public List<Spacescale> getSpacescale() {
        if (spacescale == null) {
            spacescale = new ArrayList<Spacescale>();
        }
        return this.spacescale;
    }

    /**
     * Gets the value of the otherscale property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the otherscale property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOtherscale().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Otherscale }
     * 
     * 
     */
    public List<Otherscale> getOtherscale() {
        if (otherscale == null) {
            otherscale = new ArrayList<Otherscale>();
        }
        return this.otherscale;
    }

    /**
     * Gets the value of the param property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the param property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParam().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Param }
     * 
     * 
     */
    public List<Param> getParam() {
        if (param == null) {
            param = new ArrayList<Param>();
        }
        return this.param;
    }

    /**
     * Gets the value of the ports property.
     * 
     * @return
     *     possible object is
     *     {@link Ports }
     *     
     */
    public Ports getPorts() {
        return ports;
    }

    /**
     * Sets the value of the ports property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ports }
     *     
     */
    public void setPorts(Ports value) {
        this.ports = value;
    }

    /**
     * Gets the value of the implementation property.
     * 
     * @return
     *     possible object is
     *     {@link Implementation }
     *     
     */
    public Implementation getImplementation() {
        return implementation;
    }

    /**
     * Sets the value of the implementation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Implementation }
     *     
     */
    public void setImplementation(Implementation value) {
        this.implementation = value;
    }

    /**
     * Gets the value of the extra property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extra property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExtra().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AnyContent }
     * 
     * 
     */
    public List<AnyContent> getExtra() {
        if (extra == null) {
            extra = new ArrayList<AnyContent>();
        }
        return this.extra;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the init property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoChoice }
     *     
     */
    public YesNoChoice getInit() {
        if (init == null) {
            return YesNoChoice.NO;
        } else {
            return init;
        }
    }

    /**
     * Sets the value of the init property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoChoice }
     *     
     */
    public void setInit(YesNoChoice value) {
        this.init = value;
    }

    /**
     * Gets the value of the interactive property.
     * 
     * @return
     *     possible object is
     *     {@link OptionalChoice }
     *     
     */
    public OptionalChoice getInteractive() {
        if (interactive == null) {
            return OptionalChoice.NO;
        } else {
            return interactive;
        }
    }

    /**
     * Sets the value of the interactive property.
     * 
     * @param value
     *     allowed object is
     *     {@link OptionalChoice }
     *     
     */
    public void setInteractive(OptionalChoice value) {
        this.interactive = value;
    }

    /**
     * Gets the value of the stateful property.
     * 
     * @return
     *     possible object is
     *     {@link OptionalChoice }
     *     
     */
    public OptionalChoice getStateful() {
        if (stateful == null) {
            return OptionalChoice.NO;
        } else {
            return stateful;
        }
    }

    /**
     * Sets the value of the stateful property.
     * 
     * @param value
     *     allowed object is
     *     {@link OptionalChoice }
     *     
     */
    public void setStateful(OptionalChoice value) {
        this.stateful = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the clazz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClazz() {
        return clazz;
    }

    /**
     * Sets the value of the clazz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClazz(String value) {
        this.clazz = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

}
