//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.11 at 06:37:51 PM CEST 
//


package eu.mapperproject.jmml.specification;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *       Represent a computational element.
 *     
 * 
 * <p>Java class for computationalElement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="computationalElement">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.mapper-project.eu/xmml}definition">
 *       &lt;attribute name="init" type="{http://www.mapper-project.eu/xmml}YesNoChoice" default="no" />
 *       &lt;attribute name="interactive" type="{http://www.mapper-project.eu/xmml}OptionalChoice" default="no" />
 *       &lt;anyAttribute processContents='lax'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "computationalElement")
@XmlSeeAlso({
    Mapper.class,
    Submodel.class
})
public class ComputationalElement
    extends Definition
{

    @XmlAttribute
    protected YesNoChoice init;
    @XmlAttribute
    protected OptionalChoice interactive;

    /**
     * Gets the value of the init property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoChoice }
     *     
     */
    public YesNoChoice getInit() {
        if (init == null) {
            return YesNoChoice.NO;
        } else {
            return init;
        }
    }

    /**
     * Sets the value of the init property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoChoice }
     *     
     */
    public void setInit(YesNoChoice value) {
        this.init = value;
    }

    /**
     * Gets the value of the interactive property.
     * 
     * @return
     *     possible object is
     *     {@link OptionalChoice }
     *     
     */
    public OptionalChoice getInteractive() {
        if (interactive == null) {
            return OptionalChoice.NO;
        } else {
            return interactive;
        }
    }

    /**
     * Sets the value of the interactive property.
     * 
     * @param value
     *     allowed object is
     *     {@link OptionalChoice }
     *     
     */
    public void setInteractive(OptionalChoice value) {
        this.interactive = value;
    }

}
