//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.11 at 05:21:44 PM CEST 
//


package eu.mapperproject.jmml.specification;

import eu.mapperproject.jmml.specification.graph.Child;
import eu.mapperproject.jmml.specification.graph.Numbered;
import eu.mapperproject.jmml.topology.HierarchicalDomain;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * 
 * 	    A domain and all its super-domains, separated by periods like
 *	      `domain.subdomain.subsubdomain'.
 * 	  
 * 
 * <p>Java class for domain simple type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;simpleType name="domain">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;pattern value="(\p{Pc}|\p{Pd}|\p{L}|\p{N})+(\.(\p{Pc}|\p{Pd}|\p{L}|\p{N})+)*"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "domain", propOrder = {
    "value"
})
public class Domain {
    private HierarchicalDomain domain;
	
    /**
     * 
     * 	    A domain and all its super-domains, separated by periods like
	 *	       `domain.subdomain.subsubdomain'.
     * 	  
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
	@XmlValue
    public String getValue() {
        return domain.toString();
    }

	public HierarchicalDomain getHierarchicalDomain() {
		return this.domain;
	}
	
    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
		this.domain = HierarchicalDomain.parseDomain(value);
    }
}
