//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.11 at 05:21:44 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.mapper-project.eu/xmml", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package eu.mapperproject.jmml.specification;
