//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.11 at 06:37:51 PM CEST 
//


package eu.mapperproject.jmml.specification;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SEL.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SEL">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NCName">
 *     &lt;enumeration value="finit"/>
 *     &lt;enumeration value="Oi"/>
 *     &lt;enumeration value="S"/>
 *     &lt;enumeration value="B"/>
 *     &lt;enumeration value="Of"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "SEL")
@XmlEnum
public enum SEL {

    @XmlEnumValue("finit")
    FINIT("finit"),
    @XmlEnumValue("Oi")
    OI("Oi"),
    S("S"),
    B("B"),
    @XmlEnumValue("Of")
    OF("Of");
    private final String value;

    SEL(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SEL fromValue(String v) {
        for (SEL c: SEL.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
