//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.11 at 05:21:44 PM CEST 
//


package eu.mapperproject.jmml.specification;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element ref="{http://www.mapper-project.eu/xmml}instance"/>
 *         &lt;element ref="{http://www.mapper-project.eu/xmml}coupling"/>
 *       &lt;/choice>
 *       &lt;anyAttribute processContents='lax'/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "instanceOrCoupling"
})
@XmlRootElement(name = "topology")
public class Topology {

    @XmlElements({
        @XmlElement(name = "instance", type = Instance.class),
        @XmlElement(name = "coupling", type = Coupling.class)
    })
    protected List<Object> instanceOrCoupling;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();
	
	private Map<String, Instance> instances;
	private List<Coupling> couplings;
	private boolean accessed;

	public Topology() {
		this.instances = new HashMap<String, Instance>();
		this.couplings = new ArrayList<Coupling>();
		this.accessed = false;
	}
	
    /**
     * Gets the value of the instanceOrCoupling property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the instanceOrCoupling property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInstanceOrCoupling().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Instance }
     * {@link Coupling }
     * 
     * 
     */
    public List<Object> getInstanceOrCoupling() {
        this.accessed = true;
        if (instanceOrCoupling == null) {
            instanceOrCoupling = new ArrayList<Object>();
        }
		return this.instanceOrCoupling;
    }
	
	public Map<String, Instance> getInstances() {
		this.fixValues();
		return this.instances;
	}
	
	public List<Coupling> getCouplings() {
		this.fixValues();
		return this.couplings;
	}
	
	private void fixValues() {
		if (this.accessed) {
			this.accessed = false;
			this.instances.clear();
			this.couplings.clear();
			
			for (Object o : instanceOrCoupling) {
				if (o instanceof Instance) {
					Instance inst = (Instance)o;
					this.instances.put(inst.getId(), inst);
				}
				else if (o instanceof Coupling) {
					this.couplings.add((Coupling)o);
				}
				else {
					throw new IllegalStateException("Topology contains other elements than Instances or Couplings.");
				}
			}
		}
	}

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

}
