//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.11 at 05:21:44 PM CEST 
//


package eu.mapperproject.jmml.specification;

import eu.mapperproject.jmml.specification.numerical.SIUnit;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * 
 * 	      An SI unit, written in scientific notation, but also accepting bits, bytes,
 * 	      and human-readable time indication. Conformance is evaluated with pattern
 * 	      `-?[0-9.]+([eE]-?[0-9]+)?\s*\w*'.
 * 	    
 * 
 * <p>Java class for unit simple type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;simpleType name="unit">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;whiteSpace value="collapse"/>
 *     &lt;pattern value="-?[0-9.]+([eE]-?[0-9]+)?\s*\w*"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "unit", propOrder = {
    "value"
})
public class Unit {

    @XmlValue
    protected String value;
	
	private SIUnit unit;
	
	public Unit() {
		this.unit = null;
	}

    /**
     * 
     * 	      An SI unit, written in scientific notation, but also accepting bits, bytes,
     * 	      and human-readable time indication. Conformance is evaluated with pattern
     * 	      `-?[0-9.]+([eE]-?[0-9]+)?\s*\w*'.
     * 	    
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }
	
	public SIUnit getSIUnit() {
		if (this.unit == null) {
			this.unit = SIUnit.parseSIUnit(this.value);
		}
		return this.unit;
	}

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
		this.unit = null;
    }

}
